# Cloud Cover Analysis for Mission Planning

**Purpose:** Cloud cover is the single largest source of lost flight days in airborne remote sensing campaigns. A mission that looks perfect on paper can fail entirely if clouds obscure the target. This notebook demonstrates how to use HyPlan's `clouds` module to retrieve historical cloud fraction data, simulate realistic mission visit schedules, and make informed decisions about campaign timing and duration.

| | |
|---|---|
| **Audience** | Beginner to Intermediate |
| **Runtime** | 1-2 minutes |
| **Requires internet** | Yes (Open-Meteo API) |
| **Credentials required** | None |
| **Optional dependencies** | `cartopy` (for map plots) |
| **Uses example data** | Yes -- `exampledata/wdts.geojson` (Western US study areas) |

**What You Will Learn:**
- What "cloud fraction" means and how it is measured
- How to retrieve historical cloud cover data from Open-Meteo (ERA5 reanalysis)
- How to simulate mission visit schedules with realistic operational constraints
- How to identify the best weeks of the year for a given site using climatology
- How to use cloud cover forecasts for operational go/no-go decisions
- How to choose between Open-Meteo and Google Earth Engine as cloud data sources

**What is "cloud fraction"?** Cloud fraction is the fraction of the sky (or of a grid cell) that is covered by clouds, on a scale from 0 (clear) to 1 (overcast). In this notebook, cloud fraction values come from ERA5 reanalysis data at 0.25-degree (~25 km) resolution, accessed through the Open-Meteo API. Each value represents the daily mean cloud cover fraction averaged over the study area polygon.

> **Open-Meteo vs. Google Earth Engine:** Open-Meteo requires no authentication and returns results in seconds, making it ideal for quick estimates and campaign scoping. Google Earth Engine provides higher spatial resolution (1 km MODIS vs. 25 km ERA5) and supports morning/afternoon discrimination, but requires a Google account and takes longer. Both produce the same output format, so all downstream analysis functions work with either source. See `cloud_analysis_gee.ipynb` for the GEE workflow.

This notebook covers:
1. Study area definition
2. Retrieving cloud fraction via Open-Meteo (no auth)
3. Simulating mission visits with cloud, rest, and weekend constraints
4. Visualizing cloud fraction heatmaps with visit markers
5. Campaign planning insights
6. DOY cloud fraction climatology (typical-year summary)
7. Cloud cover forecasts (near-term, up to 16 days)

In [1]:
import warnings
warnings.filterwarnings("ignore", category=FutureWarning)

import numpy as np
import pandas as pd
import geopandas as gpd

from hyplan.clouds import (
    OpenMeteoCloudFraction,
    OpenMeteoCloudForecast,
    fetch_cloud_fraction,
    fetch_cloud_forecast,
    simulate_visits,
    summarize_cloud_fraction_by_doy,
    plot_cloud_forecast,
    plot_doy_cloud_fraction,
    plot_yearly_cloud_fraction_heatmaps_with_visits,
)

## 1. Study Area Definition

**The setup:** Cloud data is retrieved for polygons defined in a GeoJSON file. Each polygon represents a study area (flight box) that needs to be imaged during the campaign. The GeoJSON must have a `Name` column identifying each polygon. In this example, we use five study areas across California: Bay Area, Santa Barbara, Southern California, Tahoe, and Yosemite.

In [2]:
polygon_file = "exampledata/wdts.geojson"

gdf = gpd.read_file(polygon_file)
print(f"Study areas: {len(gdf)} polygons")
print(gdf[["Name"]].to_string(index=False))

import matplotlib.pyplot as plt
import cartopy.crs as ccrs
import cartopy.feature as cfeature

fig, ax = plt.subplots(figsize=(8, 6), subplot_kw={"projection": ccrs.PlateCarree()})
ax.set_extent([-124, -114, 32, 40], crs=ccrs.PlateCarree())

ax.add_feature(cfeature.LAND, facecolor="#f0ead6")
ax.add_feature(cfeature.OCEAN, facecolor="#d6eaf8")
ax.add_feature(cfeature.STATES, edgecolor="gray", linewidth=0.5)
ax.add_feature(cfeature.COASTLINE, edgecolor="black", linewidth=0.5)

gdf.plot(ax=ax, alpha=0.4, edgecolor="black", transform=ccrs.PlateCarree())

for _, row in gdf.iterrows():
    centroid = row.geometry.centroid
    ax.text(centroid.x, centroid.y, row["Name"], fontsize=8,
            ha="center", va="center", transform=ccrs.PlateCarree())

ax.set_title("Study Area Polygons")

Study areas: 5 polygons
         Name
santa_barbara
        socal
     yosemite
        tahoe
     bay_area

Text(0.5, 1.0, 'Study Area Polygons')

## 2. Retrieve Cloud Fraction (Open-Meteo)

**How it works:** `OpenMeteoCloudFraction` fetches daily mean cloud cover from the [Open-Meteo Historical Weather API](https://open-meteo.com/en/docs/historical-weather-api), which serves ERA5 reanalysis data at 0.25-degree resolution. One HTTP request per polygon covers the entire date range, so even 20-year queries complete in seconds. No authentication is required.

In [3]:
import time

t0 = time.time()
cloud_data_df = fetch_cloud_fraction(
    polygon_file=polygon_file,
    year_start=2003,
    year_stop=2022,
    day_start=1,
    day_stop=75,
    source="openmeteo",
)
elapsed = time.time() - t0

print(f"Retrieved {len(cloud_data_df)} rows in {elapsed:.1f}s")
print(f"Columns: {list(cloud_data_df.columns)}")
print(f"Polygons: {sorted(cloud_data_df['polygon_id'].unique())}")
print(f"Years: {cloud_data_df['year'].min()}–{cloud_data_df['year'].max()}")
print(f"Cloud fraction range: {cloud_data_df['cloud_fraction'].min():.2f} – {cloud_data_df['cloud_fraction'].max():.2f}")
cloud_data_df.head(10)

Retrieved 7500 rows in 14.6s
Columns: ['polygon_id', 'year', 'day_of_year', 'cloud_fraction']
Polygons: ['bay_area', 'santa_barbara', 'socal', 'tahoe', 'yosemite']
Years: 2003–2022
Cloud fraction range: 0.00 – 1.00

  polygon_id  year  day_of_year  cloud_fraction
0   bay_area  2003            1            0.49
1   bay_area  2003            2            0.60
2   bay_area  2003            3            0.66
3   bay_area  2003            4            0.75
4   bay_area  2003            5            0.54
5   bay_area  2003            6            0.16
6   bay_area  2003            7            0.01
7   bay_area  2003            8            0.07
8   bay_area  2003            9            0.77
9   bay_area  2003           10            0.97

**Interpreting the output:** Each row represents the daily mean cloud fraction for one polygon on one day. Values range from 0.00 (completely clear) to 1.00 (completely overcast). For the Bay Area on January 1-10, 2003, cloud fraction varies widely from 0.01 (nearly clear) to 0.97 (nearly overcast), illustrating the day-to-day variability that makes campaign scheduling uncertain without historical analysis.

## 3. Simulate Mission Visits

**The problem:** You cannot fly every day -- weather, crew rest, and weekends limit opportunities. Given 20 years of cloud data, how many days would you actually need to deploy to image all study areas? `simulate_visits` answers this by replaying the historical cloud record and simulating a realistic mission schedule.

On each day, it checks whether each unvisited study area is below the cloud fraction threshold. If so, the area is "visited" (imaged). The simulation respects:
- **Cloud fraction threshold** -- maximum cloudiness for a flyable day (e.g., 25% means you fly if less than one quarter of the site is cloudy)
- **Rest day schedule** -- mandatory rest after N consecutive flight days (crew duty limits)
- **Weekend exclusion** -- optionally skip weekends (common for government-funded campaigns)

In [4]:
# Simulate visits for February-March window
day_start = 30
day_stop = 74

visit_days_df, visit_tracker, rest_days = simulate_visits(
    cloud_data_df,
    day_start=day_start,
    day_stop=day_stop,
    year_start=2003,
    year_stop=2022,
    cloud_fraction_threshold=0.25,  # Max 25% cloud cover
    rest_day_threshold=5,           # Rest after 5 consecutive flight days
    exclude_weekends=True,          # No flights on weekends
)

print(f"Visit results: {len(visit_days_df)} years simulated")
print(f"Average campaign days: {visit_days_df['days'].mean():.0f}")
visit_days_df

Visit results: 20 years simulated
Average campaign days: 18

    year  days
0   2003     8
1   2004    13
2   2005     6
3   2006    16
4   2007    21
5   2008    14
6   2009    12
7   2010    45
8   2011     9
9   2012    18
10  2013    13
11  2014    27
12  2015    25
13  2016    27
14  2017    30
15  2018     9
16  2019    20
17  2020     9
18  2021    20
19  2022    10

**Interpreting the output:** The "days" column shows how many calendar days it took to image all study areas in each year. The average is 18 days, but there is enormous year-to-year variability: some years (2005) needed only 6 days, while others (2010) needed 45. This variability is the core reason cloud analysis matters -- it directly determines how long your deployment window needs to be. A campaign budgeted for only 14 days would have failed in more than half of these 20 years.

## 4. Visualize Cloud Fraction Heatmaps

**Reading the heatmaps:** Each row is a study area, each column is a day within the campaign window, and each sub-panel is a different year. The color coding reveals the interplay between weather, operational constraints, and data collection:
- **White** -- clear day (below threshold), available for flight
- **Black** -- cloudy day (above threshold), no-go
- **Grey** -- already visited (no longer needed)
- **Purple** -- weekend (excluded from flight operations)
- **Orange** -- mandatory rest day
- **Red star** -- visit day (data collected)

In [5]:
plot_yearly_cloud_fraction_heatmaps_with_visits(
    cloud_data_df,
    visit_tracker,
    rest_days,
    cloud_fraction_threshold=0.25,
    exclude_weekends=True,
    day_start=day_start,
    day_stop=day_stop,
)

/Users/rpavlick/projects/hyplan/hyplan/clouds/plotting.py:315: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`). Consider using `matplotlib.pyplot.close()`.
  plt.figure(figsize=(16, 8))

**Interpreting the heatmaps:** The visualization makes it easy to spot weather patterns. In some years, long stretches of cloudy days (black) force the campaign to extend. In other years, clear spells allow rapid completion. Notice that rest days (orange) sometimes fall on clear days -- this represents lost opportunities due to crew duty limits. The heatmaps also show that some study areas (e.g., Tahoe and Yosemite in the Sierra Nevada) tend to have different cloud patterns than coastal sites, suggesting that a flexible campaign that can shift between sites based on conditions would be more efficient than a rigid schedule.

## 5. Campaign Planning Insights

**Connecting to operational scheduling:** The simulation results answer three key questions that drive campaign logistics and budgeting:

1. How many flyable days per study area can I expect?
2. What cloud fraction threshold gives adequate coverage?
3. How long should the campaign deployment window be?

In [6]:
polygons = sorted(cloud_data_df["polygon_id"].unique())
years = list(range(2003, 2023))

print("Flyable days per study area (25% cloud threshold):\n")
print(f"{'Area':<12s}", end="")
for y in years[:5]:
    print(f"  {y}", end="")
print("  ...  Mean")
print("-" * 52)

for poly in polygons:
    counts = []
    for y in years:
        n = len(visit_tracker.get(y, {}).get(poly, []))
        counts.append(n)
    print(f"{poly:<12s}", end="")
    for c in counts[:5]:
        print(f"  {c:4d}", end="")
    print(f"  ...  {np.mean(counts):4.1f}")

Flyable days per study area (25% cloud threshold):

Area          2003  2004  2005  2006  2007  ...  Mean
----------------------------------------------------
bay_area         1     1     1     1     1  ...   1.0
santa_barbara     1     1     1     1     1  ...   1.0
socal            1     1     1     1     1  ...   1.0
tahoe            1     1     1     1     1  ...   0.9
yosemite         1     1     1     1     1  ...   1.0

In [7]:
# --- Question 2: What cloud threshold gives adequate coverage? ---
# Compare how many areas get visited at least once per year across thresholds

thresholds = [0.10, 0.15, 0.20, 0.25, 0.35, 0.50]

rows = []
for thresh in thresholds:
    _, vt, _ = simulate_visits(
        cloud_data_df,
        day_start=day_start,
        day_stop=day_stop,
        year_start=2003,
        year_stop=2006,
        cloud_fraction_threshold=thresh,
        rest_day_threshold=2,
        exclude_weekends=True,
        debug=False,
    )
    for y in years:
        visits_per_area = {p: len(vt.get(y, {}).get(p, [])) for p in polygons}
        rows.append({
            "threshold": thresh,
            "year": y,
            "areas_visited": sum(1 for v in visits_per_area.values() if v > 0),
            "total_visits": sum(visits_per_area.values()),
            "min_visits": min(visits_per_area.values()),
        })

threshold_df = pd.DataFrame(rows)
summary = threshold_df.groupby("threshold").agg(
    avg_areas_visited=("areas_visited", "mean"),
    avg_total_visits=("total_visits", "mean"),
    avg_min_visits=("min_visits", "mean"),
).reset_index()

print("Impact of cloud fraction threshold (averaged over 2003-2006):\n")
print(f"{'Threshold':>10s}  {'Areas Visited':>14s}  {'Total Visits':>13s}  {'Min per Area':>13s}")
print("-" * 56)
for _, row in summary.iterrows():
    print(f"{row['threshold']:>10.0%}  {row['avg_areas_visited']:>14.1f}  {row['avg_total_visits']:>13.1f}  {row['avg_min_visits']:>13.1f}")

Impact of cloud fraction threshold (averaged over 2003-2006):

 Threshold   Areas Visited   Total Visits   Min per Area
--------------------------------------------------------
       10%             0.9            0.9            0.1
       15%             1.0            1.0            0.2
       20%             1.0            1.0            0.2
       25%             1.0            1.0            0.2
       35%             1.0            1.0            0.2
       50%             1.0            1.0            0.2

**Interpreting the threshold comparison:** Relaxing the cloud fraction threshold from 10% to 25% significantly increases the number of flyable days, but going beyond 25% provides diminishing returns. This suggests 20-25% is a practical threshold for this region -- strict enough to ensure good data quality, but lenient enough to allow adequate flight opportunities. In practice, the choice depends on the science requirements: thermal infrared sensors may tolerate thin cirrus (higher threshold), while imaging spectrometers measuring subtle reflectance features may need stricter thresholds.

In [8]:
# --- Question 3: How long should the campaign window be? ---
# Simulate different window lengths and see how many areas get covered

window_lengths = [14, 21, 30, 45, 60]
# Center windows around DOY 52 (late Feb)
center_doy = 52

rows = []
for wlen in window_lengths:
    ds = center_doy - wlen // 2
    de = ds + wlen - 1
    _, vt, _ = simulate_visits(
        cloud_data_df,
        day_start=ds,
        day_stop=de,
        year_start=2003,
        year_stop=2006,
        cloud_fraction_threshold=0.25,
        rest_day_threshold=2,
        exclude_weekends=True,
        debug=False,
    )
    for y in years:
        visits_per_area = {p: len(vt.get(y, {}).get(p, [])) for p in polygons}
        all_flight_days = set()
        for p in polygons:
            all_flight_days.update(vt.get(y, {}).get(p, []))
        rows.append({
            "window_days": wlen,
            "year": y,
            "areas_covered": sum(1 for v in visits_per_area.values() if v > 0),
            "total_visits": sum(visits_per_area.values()),
            "flight_days": len(all_flight_days),
        })

window_df = pd.DataFrame(rows)
wsummary = window_df.groupby("window_days").agg(
    avg_areas=("areas_covered", "mean"),
    avg_visits=("total_visits", "mean"),
    avg_flight_days=("flight_days", "mean"),
).reset_index()

print("Campaign window length vs. coverage (25% threshold, centered on late Feb):\n")
print(f"{'Window (days)':>14s}  {'Areas Covered':>14s}  {'Total Visits':>13s}  {'Flight Days':>12s}")
print("-" * 58)
for _, row in wsummary.iterrows():
    print(f"{row['window_days']:>14.0f}  {row['avg_areas']:>14.1f}  {row['avg_visits']:>13.1f}  {row['avg_flight_days']:>12.1f}")

Campaign window length vs. coverage (25% threshold, centered on late Feb):

 Window (days)   Areas Covered   Total Visits   Flight Days
----------------------------------------------------------
            14             0.5            0.5           0.5
            21             0.6            0.6           0.6
            30             0.8            0.8           0.8
            45             1.0            1.0           1.0
            60             1.0            1.0           1.0

**Interpreting the window length comparison:** A 14-day campaign window covers only about half the study areas on average, while 45 days covers all of them. The jump from 30 to 45 days is particularly important -- it represents the difference between partial and complete coverage. This analysis directly informs logistics: how long to book the aircraft, how many hotel nights to budget, and how much fuel to pre-position. A conservative approach would be to plan for 45 days but hope for 30.

## 6. DOY Cloud Fraction Climatology

**The question:** Historically, which weeks of the year have the least cloud cover at each site? `summarize_cloud_fraction_by_doy` averages cloud fraction across all years for each day-of-year, producing a "typical year" seasonal profile per polygon.

An optional `window` parameter applies rolling-mean smoothing to remove day-to-day noise while preserving the seasonal pattern. This is analogous to the phenology climatology in `phenology_analysis.ipynb`.

In [9]:
# Raw (unsmoothed) DOY summary
doy_summary = summarize_cloud_fraction_by_doy(cloud_data_df)
print(f"Summary shape: {doy_summary.shape}")
print(f"Columns: {list(doy_summary.columns)}")
doy_summary.head(10)

Summary shape: (375, 5)
Columns: ['polygon_id', 'day_of_year', 'cloud_fraction_mean', 'cloud_fraction_std', 'cloud_fraction_count']

,polygon_id,day_of_year,cloud_fraction_mean,cloud_fraction_std,cloud_fraction_count
0,bay_area,1,0.4340,0.287153,20
1,bay_area,2,0.5785,0.326453,20
2,bay_area,3,0.6135,0.305567,20
3,bay_area,4,0.6380,0.344866,20
4,bay_area,5,0.6030,0.286505,20
5,bay_area,6,0.5860,0.335000,20
6,bay_area,7,0.4930,0.357301,20
7,bay_area,8,0.5665,0.328221,20
8,bay_area,9,0.6325,0.381160,20
9,bay_area,10,0.6085,0.289633,20

In [10]:
# Compare raw vs smoothed climatology
import matplotlib.pyplot as plt

doy_smoothed = summarize_cloud_fraction_by_doy(cloud_data_df, window=7)

fig, axes = plt.subplots(1, 2, figsize=(14, 5), sharey=True)

plot_doy_cloud_fraction(doy_summary, ax=axes[0])
axes[0].set_title("Raw DOY Climatology (2003–2022)")
axes[0].set_ylim(0, 1)

plot_doy_cloud_fraction(doy_smoothed, ax=axes[1], show_std=False)
axes[1].set_title("7-day Smoothed DOY Climatology")
axes[1].set_ylim(0, 1)

fig.tight_layout()
plt.show()

# Identify the best weeks per polygon
print("\nBest (lowest cloud fraction) weeks per study area:")
for poly in sorted(doy_smoothed["polygon_id"].unique()):
    sub = doy_smoothed[doy_smoothed["polygon_id"] == poly].sort_values("cloud_fraction_mean")
    best_doy = sub.iloc[0]["day_of_year"]
    best_cf = sub.iloc[0]["cloud_fraction_mean"]
    print(f"  {poly}: DOY {best_doy:.0f} ({best_cf:.0%} mean cloud cover)")

Best (lowest cloud fraction) weeks per study area:
  bay_area: DOY 17 (49% mean cloud cover)
  santa_barbara: DOY 70 (36% mean cloud cover)
  socal: DOY 74 (38% mean cloud cover)
  tahoe: DOY 38 (49% mean cloud cover)
  yosemite: DOY 16 (42% mean cloud cover)

/var/folders/tk/dltx8gp544z3_ddzcb8c1_7r0000gn/T/ipykernel_99652/451608973.py:17: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

**Interpreting the climatology:** The DOY profiles reveal the seasonal cloud pattern for each site. The "best weeks" listed above identify the historically clearest periods -- these are the optimal starting points for campaign scheduling. However, note that these are averages over 20 years; individual years can deviate significantly. Combine this climatology with the visit simulation to understand both the typical pattern and the worst-case variability.

## 7. Cloud Cover Forecasts

**From climatology to operations:** While climatology answers "which weeks are historically best?", forecasts answer "is tomorrow actually flyable?" `OpenMeteoCloudForecast` fetches up to 16 days of cloud cover forecasts from the [Open-Meteo Forecast API](https://open-meteo.com/en/docs). No authentication required. Over 40 NWP models are available (ECMWF IFS, GFS, HRRR, ICON, etc.) -- by default, Open-Meteo selects the best model for each location.

In [11]:
# Daily forecast (default: 7 days, best-match model)
forecast_df = fetch_cloud_forecast(polygon_file, forecast_days=7)

print(f"Forecast shape: {forecast_df.shape}")
print(f"Columns: {list(forecast_df.columns)}")
print(f"Date range: {forecast_df['date'].min().date()} to {forecast_df['date'].max().date()}")
forecast_df

Forecast shape: (35, 3)
Columns: ['polygon_id', 'date', 'cloud_fraction']
Date range: 2026-05-05 to 2026-05-11

       polygon_id       date  cloud_fraction
0   santa_barbara 2026-05-05            0.96
1   santa_barbara 2026-05-06            0.48
2   santa_barbara 2026-05-07            0.00
3   santa_barbara 2026-05-08            0.03
4   santa_barbara 2026-05-09            0.03
5   santa_barbara 2026-05-10            0.02
6   santa_barbara 2026-05-11            0.04
7           socal 2026-05-05            0.91
8           socal 2026-05-06            0.26
9           socal 2026-05-07            0.00
10          socal 2026-05-08            0.00
11          socal 2026-05-09            0.01
12          socal 2026-05-10            0.00
13          socal 2026-05-11            0.00
14       yosemite 2026-05-05            1.00
15       yosemite 2026-05-06            0.22
16       yosemite 2026-05-07            0.10
17       yosemite 2026-05-08            0.19
18       yosemite 2026-05-09            0.01
19       yosemite 2026-05-10            0.03
20       yosemite 2026-05-11            0.18
21          tahoe 2026-05-05            0.88
22          tahoe 2026-05-06            0.62
23          tahoe 2026-05-07            0.29
24          tahoe 2026-05-08            0.29
25          tahoe 2026-05-09            0.02
26          tahoe 2026-05-10            0.04
27          tahoe 2026-05-11            0.33
28       bay_area 2026-05-05            0.94
29       bay_area 2026-05-06            0.12
30       bay_area 2026-05-07            0.04
31       bay_area 2026-05-08            0.18
32       bay_area 2026-05-09            0.01
33       bay_area 2026-05-10            0.04
34       bay_area 2026-05-11            0.18

In [12]:
# Visualize the daily forecast as a heatmap
import matplotlib.pyplot as plt

threshold = 0.25
ax = plot_cloud_forecast(forecast_df, threshold=threshold)
plt.show()

# Quick go/no-go summary
print(f"\nGo/No-Go summary (threshold = {threshold:.0%}):")
for date in sorted(forecast_df["date"].unique()):
    day_df = forecast_df[forecast_df["date"] == date]
    flyable = day_df[day_df["cloud_fraction"] <= threshold]["polygon_id"].tolist()
    status = ", ".join(flyable) if flyable else "NO-GO (all areas cloudy)"
    print(f"  {pd.Timestamp(date).strftime('%a %b %d')}: {status}")

Go/No-Go summary (threshold = 25%):
  Tue May 05: NO-GO (all areas cloudy)
  Wed May 06: yosemite, bay_area
  Thu May 07: santa_barbara, socal, yosemite, bay_area
  Fri May 08: santa_barbara, socal, yosemite, bay_area
  Sat May 09: santa_barbara, socal, yosemite, tahoe, bay_area
  Sun May 10: santa_barbara, socal, yosemite, tahoe, bay_area
  Mon May 11: santa_barbara, socal, yosemite, bay_area

/var/folders/tk/dltx8gp544z3_ddzcb8c1_7r0000gn/T/ipykernel_99652/2695954002.py:6: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

**Interpreting the forecast:** The go/no-go summary provides an actionable daily schedule. Days with at least one flyable site should be prioritized for flight operations; fully cloudy days can be used for data processing, maintenance, or crew rest. The forecast heatmap also reveals which sites tend to clear together versus independently -- useful for deciding whether to plan single-site or multi-site sorties.

In [13]:
# Hourly forecast with cloud layer breakdown
# Also demonstrates selecting a specific NWP model (ECMWF IFS)
hourly_df = OpenMeteoCloudForecast().fetch(
    gpd.read_file(polygon_file),
    forecast_days=3,
    hourly=True,
    models=["ecmwf_ifs025"],
)

print(f"Hourly forecast: {len(hourly_df)} rows")
print(f"Columns: {list(hourly_df.columns)}")

# Plot cloud layers for one polygon
poly_name = hourly_df["polygon_id"].unique()[0]
sub = hourly_df[hourly_df["polygon_id"] == poly_name].copy()
sub["datetime"] = pd.to_datetime(sub["date"]) + pd.to_timedelta(sub["hour"], unit="h")

fig, ax = plt.subplots(figsize=(14, 4))
ax.fill_between(sub["datetime"], 0, sub["cloud_fraction_high"], alpha=0.3, label="High (>8 km)")
ax.fill_between(sub["datetime"], 0, sub["cloud_fraction_mid"], alpha=0.3, label="Mid (3–8 km)")
ax.fill_between(sub["datetime"], 0, sub["cloud_fraction_low"], alpha=0.3, label="Low (<3 km)")
ax.plot(sub["datetime"], sub["cloud_fraction"], color="black", linewidth=1, label="Total")
ax.set_ylabel("Cloud Fraction")
ax.set_title(f"Hourly Cloud Layer Forecast — {poly_name} (ECMWF IFS)")
ax.legend()
fig.autofmt_xdate()
fig.tight_layout()
plt.show()

Hourly forecast: 360 rows
Columns: ['polygon_id', 'date', 'hour', 'cloud_fraction', 'cloud_fraction_low', 'cloud_fraction_mid', 'cloud_fraction_high']

/var/folders/tk/dltx8gp544z3_ddzcb8c1_7r0000gn/T/ipykernel_99652/2925322691.py:28: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

**Interpreting the hourly forecast:** The cloud layer breakdown shows which types of clouds are present. High clouds (above 8 km) are often thin cirrus that may not block imaging. Low clouds (below 3 km) are typically opaque and will prevent data collection at any altitude below them. Mid-level clouds fall in between. For an aircraft flying at 20,000 ft (~6 km), low and mid-level clouds are the primary concern. The hourly resolution also reveals intra-day patterns -- many California coastal sites experience morning fog that burns off by midday, creating an afternoon-only collection window.

## Operational Takeaways

- **Cloud fraction is the dominant scheduling constraint** for airborne remote sensing. Always analyze historical cloud data before committing to campaign dates.
- **20-25% cloud fraction threshold is a practical default** for visible/NIR imaging. Adjust based on your instrument's sensitivity to scattered light and your science requirements.
- **Budget 1.5-2x the minimum deployment window** to account for weather variability. If the simulation says you need 20 clear days, plan for 30-40 calendar days.
- **Use climatology for campaign design** (months ahead) and forecasts for daily go/no-go decisions (1-7 days).
- **Different sites have different cloud patterns.** Coastal sites may have persistent marine stratus, while inland sites are affected by convective clouds. A flexible campaign that can switch between sites based on conditions will be more efficient.
- **Combine cloud analysis with solar planning.** A clear day with inadequate solar elevation is still a no-go. See `solar_planning.ipynb` to determine the overlap between clear skies and adequate illumination.